### ISSUE TITLE
New Matcher: .toBeWithin(start, end)

### ISSUE THREAD

**Issue by mattphillips** [mattphillips/jest-extended#10]
**Feature Request**

Description:

### .toBeWithin(start, end)

Use `.toBeWithin` when checking if a number is in between the given bounds of: start (inclusive) and end (exclusive).

```js
test('passes when number is within given bounds', () => {
  expect(1).toBeWithin(1, 3);
  expect(2).toBeWithin(1, 3);
  expect(3).not.toBeWithin(1, 3);
});
```

**Comment by martiuslim** [comment]
hi, I'd like to try this

**Comment by mattphillips** [comment]
all yours @martiuslim remember to star and share :smile:
