### ISSUE TITLE
New Matcher: .toContainAllKeys([keys])

### ISSUE THREAD

**Issue by mattphillips** [mattphillips/jest-extended#13]
**Feature Request**

### .toContainAllKeys([keys])

Use `.toContainAllKeys` when checking if an object only contains all of the provided keys.

```js
test('passes when object only contains all keys', () => {
  const o = { a: 'hello', b: 'world' };
  expect(o).toContainAllKeys(['a', 'b']);
  expect(o).toContainAllKeys(['b', 'a']);
  expect(o).not.toContainAllKeys(['b']);
});
```

**Comment by marcinlichwala** [comment]
Hello @mattphillips,
I would like to take this one :)

**Comment by mattphillips** [comment]
Thanks @marcinlichwala

**Comment by GitHug** [comment]
Oh maaan! I was investigating this one and ended up coming up with a solution. Didn't think about claiming it until it was too late. You snooze you loose, I guess...

I am ready to create the pull request, but I will let @marcinlichwala handle this one. Let me know if I should create the PR :)

**Comment by marcinlichwala** [comment]
That is fine, you can take this one, obviously :)

**Comment by GitHug** [comment]
Thanks @marcinlichwala I will check the comments in the issue more carefully next time so there are no double work 👍
