### ISSUE TITLE
New Matcher: .toContainAnyValues([values])

### ISSUE THREAD

**Issue by mattphillips** [mattphillips/jest-extended#16]
**Feature Request**

### .toContainAnyValues([values])

Use `.toContainAnyValues` when checking if an object contains at least one of the provided values.

```js
test('passes when object contains at least one of the given values', () => {
  const o = { a: 'foo', b: 'bar', c: 'baz' };
  expect(o).toContainAnyValues(['qux', 'foo']);
  expect(o).toContainAnyValues(['qux', 'bar']);
  expect(o).toContainAnyValues(['qux', 'baz']);
  expect(o).not.toContainAnyValues(['qux']);
});
```

**Comment by deerawan** [comment]
@mattphillips can I grab this one?

**Comment by mattphillips** [comment]
All yours @deerawan :smile: if you can star the project 🌟 that would be awesome!

**Comment by deerawan** [comment]
@mattphillips will inner object be covered in the command?

**Comment by mattphillips** [comment]
@deerawan yeah it should cover nested values i.e. objects/arrays/etc
