### ISSUE TITLE
New Matcher:  .toContainEntry([key, value])

### ISSUE THREAD

**Issue by mattphillips** [mattphillips/jest-extended#17]
**Feature Request**

### .toContainEntry([key, value])

Use `.toContainEntry` when checking if an object contains the provided entry.

```js
test('passes when object contains given entry', () => {
  const o = { a: 'foo', b: 'bar', c: 'baz' };
  expect(o).toContainEntry(['a', 'foo']);
  expect(o).toContainEntry(['b', 'bar']);
  expect(o).toContainEntry(['c', 'baz']);
  expect(o).not.toContainEntry(['a', 'qux']);
});
```

**Comment by grug** [comment]
I'll take this one.

**Comment by mattphillips** [comment]
you got @grug :smile:

**Comment by grug** [comment]
Thanks @danielr18 for stealing this from me - classy!

**Comment by mattphillips** [comment]
Hey @grug if you have worked on this then still send a PR as you claimed it first!

**Comment by danielr18** [comment]
Sorry @grug, my bad. I started it before you commented on it, it was my first PR on the project so I didn't know I had to leave a comment. I did that in the other issues to avoid this.

**Comment by grug** [comment]
Haha I re-read my comment and realised that it sounded way harsher than I meant it to! I was just messing around, it's all good :) I was too slow!

**Comment by grug** [comment]
Once again, super sorry for coming across the way I did originally! I really didn't mean for it to be like that. Definitely accept @danielr18's PR as it's good and he beat me to it.

**Comment by mattphillips** [comment]
I've just added a small comment to #69 for deep equality not sure if you guys want to collaborate on that?

**Comment by danielr18** [comment]
No probs @grub, all good. Do you want to implement the change?

**Comment by grug** [comment]
All good @danielr18, it's all yours :)
