### ISSUE TITLE
New Matcher: .toBeExtensible()

### ISSUE THREAD

**Issue by mattphillips** [mattphillips/jest-extended#25]
**Feature Request**

### .toBeExtensible()

Use `.toBeExtensible` when checking if an object is extensible.

```js
test('passes when value is extensible', () => {
  expect({a: 1}).toBeExtensible();
  expect(1).not.toBeExtensible();
});
```

**Comment by tjwhalen16** [comment]
I'll give this one a try

**Comment by mattphillips** [comment]
@tjwhalen16 all yours buddy! Don't forget to star ✨ and share the project 😄
