### ISSUE TITLE
New Matcher: .toBeFinite()

### ISSUE THREAD

**Issue by mattphillips** [mattphillips/jest-extended#28]
**Feature Request**

### .toBeFinite()

Use `.toBeFinite` when checking if a value is a `Number`, not `NaN` or `Infinity`.

```js
test('passes when value is a finite number', () => {
  expect(1).toBeFinite();
  expect(Infinity).not.toBeFinite();
  expect(NaN).not.toBeFinite();
});
```

**Comment by tophernuts** [comment]
I'll have a PR up for this in a bit!

**Comment by mattphillips** [comment]
Nice one @tophernuts. Don't forget to star ✨ and share the project 😄
