### ISSUE TITLE
New Matcher: .toBePositive()

### ISSUE THREAD

**Issue by mattphillips** [mattphillips/jest-extended#29]
**Feature Request**

### .toBePositive()

Use `.toBePositive` when checking if a value is a positive `Number`.

```js
test('passes when value is a positive number', () => {
  expect(1).toBePositive();
  expect(Infinity).not.toBePositive();
  expect(-1).not.toBePositive();
  expect(NaN).not.toBePositive();
});
```

**Comment by hydrabolt** [comment]
I'll take this one :)

**Comment by vteremasov** [comment]
Oh sorry

**Comment by vteremasov** [comment]
I already commited (

**Comment by khorramk** [comment]
can i contribute to this?
i will like to take this

**Comment by mattphillips** [comment]
Hey @khorramk unfortunately I think @vteremasov has already sent a pr (#57) for this one. I have a whole list of more matchers to add to jest-extended (once I get through merging all of the amazing work everyone has done) so just keep your eyes peeled and there will be some more soon to do :smile:
