### ISSUE TITLE
New Matcher: .toBeBoolean()

### ISSUE THREAD

**Issue by mattphillips** [mattphillips/jest-extended#38]
**Feature Request**

### .toBeBoolean()

Use `.toBeBoolean` when checking if a value is a `Boolean`.

```js
test('passes when value is a boolean', () => {
  expect(false).toBeBoolean();
  expect(true).toBeBoolean();
  expect(1 === 1).toBeBoolean();
  expect(1).not.toBeBoolean();
});
```

**Comment by m13m** [comment]
I wish to work on this.

**Comment by mattphillips** [comment]
All yours :smile:

**Comment by subinoy7** [comment]
Hi @mattphillips ,
I am new at node.js, and I tried to implement this functionality. Can you please check it or give me instructions to check it myself in my local machine.

**Comment by GitHug** [comment]
Is anyone working on this one still? Otherwise I can implement this.

**Comment by m13m** [comment]
@GitHug You can take this.

**Comment by mattphillips** [comment]
@GitHug I think @subinoy7 had made a start on this in #71 perhaps you could lend a hand as they are new to node?

**Comment by subinoy7** [comment]
@GitHug you can take this, @mattphillips  I couldn’t complete this because I am not able to test it locally, I will learn this soon, thanks for your support🤗, also I can compare my code with @GitHug to learn I guess!

**Comment by GitHug** [comment]
Created PR #88
 
@subinoy7 to get started with node.js I would advice you to experiment with this repo by either forking it or just cloning it from here. Once you have it on your local machine, provided that you have npm, cd to the directory and run
```
npm install
```
To download all the dependencies for the project. You can run all the tests in the project with 
```
npm test
```
To add a new matcher to the project have a look at src/matchers. Create a new directory
```
mkdir toBeANewMatcher
```
That will hold all the tests and implementation for the feature. The directory should contain 4 files

```
1. index.js - Contains implementation for the matcher
2. index.test.js - Contains tests for the matcher
3. predicate.js - Evaluates the value given by the matcher that should evaluate as true if as expected
4. predicate.test.js - Test for predicate.js
```
When you believe you have created something that works just run `npm test` (or `npm test src/matchers/toBeANewMatcher` to run tests for a specific matcher) and keep your fingers crossed that everything works as expected :stuck_out_tongue_winking_eye:

I hope these instructions gave you a brief introduction on how to get started. Best for learning, for me at least, is just to do stuff and break things. So just experiment :grinning:

I am no super expert at node.js, I just think it's fun, so if anyone feels that there is something to add, then feel free!

**Comment by subinoy7** [comment]
@GitHug thanks for sharing, yeah I agree that experiment is the quickest way to learn something :) thanks for guiding. Thanks to @mattphillips  also for bringing up this discussion.

**Comment by subinoy7** [comment]
@GitHug can you help me why I am getting this only in Travis CI but not getting it when testing it locally
    expect(value).toMatchSnapshot()
    New snapshot was not written. The update flag must be explicitly passed to write a new snapshot.
    This is likely because this test is run in a continuous integration (CI) environment in which snapshots are not written by default.
