### ISSUE TITLE
New Matcher:  .toEndWith(suffix)

### ISSUE THREAD

**Issue by mattphillips** [mattphillips/jest-extended#40]
**Feature Request**

### .toEndWith(suffix)

Use `.toEndWith` when checking if a `String` ends with a given `String` suffix.

```js
test('passes when value is ends with given string', () => {
  expect('hello world').toEndWith('world');
  expect('hello world').not.toEndWith('hello');
});
```

**Comment by marcinlichwala** [comment]
Hello @mattphillips! I would like to take this one :)

**Comment by mattphillips** [comment]
Thanks @marcinlichwala!
