### ISSUE TITLE
New Matcher: .toInclude(substring)

### ISSUE THREAD

**Issue by mattphillips** [mattphillips/jest-extended#41]
**Feature Request**

### .toInclude(substring)

Use `.toInclude` when checking if a `String` includes the given `String` substring.

```js
test('passes when value includes substring', () => {
  expect('hello world').toInclude('ell');
  expect('hello world').not.toInclude('bob');
});
```

**Comment by arcticbarra** [comment]
I'll take this one 👍

**Comment by mattphillips** [comment]
Nice one! Let me know if you need a hand :smile:

**Comment by grug** [comment]
Hey @mattphillips I've noticed there hasn't been any movement on this in 3 days so I might have a crack and if @arcticbarra wants to collab or submit their own PR then you can take that. Hopefully that's cool.
