### ISSUE TITLE
New Matcher: .toIncludeMultiple([substring])

### ISSUE THREAD

**Issue by mattphillips** [mattphillips/jest-extended#43]
**Feature Request**

### .toIncludeMultiple([substring])

Use `.toIncludeMultiple` when checking if a `String` includes all of the given substrings.

```js
test('passes when value includes all substrings', () => {
  expect('hello world').toInclude(['world', 'hello']);
  expect('hello world').not.toInclude(['world', 'hello', 'bob']);
});
```

**Comment by m13m** [comment]
I wish to work on this.

**Comment by ecollis6** [comment]
Hey, I'd like to give this a shot. I'll have a PR ready ASAP :)
