### ISSUE TITLE
New Matcher:  .toEqualIgnoringCase(string)

### ISSUE THREAD

**Issue by mattphillips** [mattphillips/jest-extended#44]
**Feature Request**

### .toEqualIgnoringCase(string)

Use `.toEqualIgnoringCase` when checking if a string is equal (===) to another ignoring the casing of both strings.

```js
test('passes when strings are equal ignoring case', () => {
  expect('hello world').toEqualIgnoringCase('hello world');
  expect('hello WORLD').toEqualIgnoringCase('HELLO world');
  expect('HELLO WORLD').toEqualIgnoringCase('hello world');
  expect('hello world').toEqualIgnoringCase('HELLO WORLD');
  expect('hello world').not.toEqualIgnoringCase('hello');
});
```

**Comment by btnwtn** [comment]
I got this! 🙌

**Comment by mattphillips** [comment]
Nice one! Let me know if you need a hand :smile:

**Comment by btnwtn** [comment]
I've renamed the matcher because I think CaseInsensitive makes more sense. Also easier to read with different fonts. Let me know what you think.

**Comment by mattphillips** [comment]
First one to be merged 🎉
