### ISSUE TITLE
New Matcher: .toBeEmpty()

### ISSUE THREAD

**Issue by mattphillips** [mattphillips/jest-extended#9]
**Feature Request**

Description:

### .toBeEmpty()

Use `.toBeEmpty` when checking if a `String` `''`, `Array` `[]` or `Object` `{}` is empty.

```js
test('passes when given an empty string', () => {
  expect('').toBeEmpty();
  expect('hello').not.toBeEmpty();
});

test('passes when given an empty array', () => {
  expect([]).toBeEmpty();
  expect(['hello']).not.toBeEmpty();
});

test('passes when given an empty object', () => {
  expect({}).toBeEmpty();
  expect({ hello: 'world' }).not.toBeEmpty();
});
```

**Comment by martiuslim** [comment]
I'll tackle this too 😄

**Comment by olsio** [comment]
I have a PR but introduced lodash to handle the actual check. I think lodash will help with lots of the desired matchers but I am not sure what the policy is on new dependencies. I just think lodash is very stable and battle proven and will give is better results.

**Comment by subinoy7** [comment]
@mattphillips Is anyone working on this? I wish to work on this.
